services:
  php_resale_panter:
    hostname: resale_panter
    build: docker/php/.
    image: php_resale_panter:fpm-alpine
    container_name: php_resale_panter
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - docker_server_caddy
    ports:
      - "${HTTP_PORT}:9000"

networks:
  docker_server_caddy:
    external: true